# False/distractor sentences for 103 N5 kanji
# Each sentence contains the target kanji but uses it incorrectly

FALSE_SENTENCES = {
    "一": [
        {
            "text_jp": "一はとてもおいしいです。",
            "furigana": "いちはとてもおいしいです。",
            "romaji": "Ichi wa totemo oishii desu.",
            "translation": "El uno es muy sabroso.",
            "is_correct": False,
        },
        {
            "text_jp": "一を飲みました。",
            "furigana": "いちをのみました。",
            "romaji": "Ichi o nomimashita.",
            "translation": "Bebí el uno.",
            "is_correct": False,
        },
        {
            "text_jp": "一が学校に来ました。",
            "furigana": "いちががっこうにきました。",
            "romaji": "Ichi ga gakkō ni kimashita.",
            "translation": "El uno vino a la escuela.",
            "is_correct": False,
        },
    ],
    "二": [
        {
            "text_jp": "二を飲みます。",
            "furigana": "にをのみます。",
            "romaji": "Ni o nomimasu.",
            "translation": "Bebo el dos.",
            "is_correct": False,
        },
        {
            "text_jp": "二はあかいです。",
            "furigana": "にはあかいです。",
            "romaji": "Ni wa akai desu.",
            "translation": "El dos es rojo.",
            "is_correct": False,
        },
        {
            "text_jp": "二が話します。",
            "furigana": "にがはなします。",
            "romaji": "Ni ga hanashimasu.",
            "translation": "El dos habla.",
            "is_correct": False,
        },
    ],
    "三": [
        {
            "text_jp": "三を食べました。",
            "furigana": "さんをたべました。",
            "romaji": "San o tabemashita.",
            "translation": "Comí el tres.",
            "is_correct": False,
        },
        {
            "text_jp": "三が学校へ行きます。",
            "furigana": "さんががっこうへいきます。",
            "romaji": "San ga gakkō e ikimasu.",
            "translation": "El tres va a la escuela.",
            "is_correct": False,
        },
        {
            "text_jp": "三はおいしいです。",
            "furigana": "さんはおいしいです。",
            "romaji": "San wa oishii desu.",
            "translation": "El tres es delicioso.",
            "is_correct": False,
        },
    ],
    "四": [
        {
            "text_jp": "四を飲みます。",
            "furigana": "よんをのみます。",
            "romaji": "Yon o nomimasu.",
            "translation": "Bebo el cuatro.",
            "is_correct": False,
        },
        {
            "text_jp": "四が走ります。",
            "furigana": "よんがはしります。",
            "romaji": "Yon ga hashirimasu.",
            "translation": "El cuatro corre.",
            "is_correct": False,
        },
        {
            "text_jp": "四は赤いです。",
            "furigana": "よんはあかいです。",
            "romaji": "Yon wa akai desu.",
            "translation": "El cuatro es rojo.",
            "is_correct": False,
        },
    ],
    "五": [
        {
            "text_jp": "五を食べます。",
            "furigana": "ごをたべます。",
            "romaji": "Go o tabemasu.",
            "translation": "Como el cinco.",
            "is_correct": False,
        },
        {
            "text_jp": "五が来ました。",
            "furigana": "ごがきました。",
            "romaji": "Go ga kimashita.",
            "translation": "El cinco vino.",
            "is_correct": False,
        },
        {
            "text_jp": "五はあまいです。",
            "furigana": "ごはあまいです。",
            "romaji": "Go wa amai desu.",
            "translation": "El cinco es dulce.",
            "is_correct": False,
        },
    ],
    "六": [
        {
            "text_jp": "六を飲みました。",
            "furigana": "ろくをのみました。",
            "romaji": "Roku o nomimashita.",
            "translation": "Bebí el seis.",
            "is_correct": False,
        },
        {
            "text_jp": "六は青いです。",
            "furigana": "ろくはあおいです。",
            "romaji": "Roku wa aoi desu.",
            "translation": "El seis es azul.",
            "is_correct": False,
        },
        {
            "text_jp": "六が話します。",
            "furigana": "ろくがはなします。",
            "romaji": "Roku ga hanashimasu.",
            "translation": "El seis habla.",
            "is_correct": False,
        },
    ],
    "七": [
        {
            "text_jp": "七を食べます。",
            "furigana": "ななをたべます。",
            "romaji": "Nana o tabemasu.",
            "translation": "Como el siete.",
            "is_correct": False,
        },
        {
            "text_jp": "七が歩きます。",
            "furigana": "なながあるきます。",
            "romaji": "Nana ga arukimasu.",
            "translation": "El siete camina.",
            "is_correct": False,
        },
        {
            "text_jp": "七はおいしいです。",
            "furigana": "ななはおいしいです。",
            "romaji": "Nana wa oishii desu.",
            "translation": "El siete es delicioso.",
            "is_correct": False,
        },
    ],
    "八": [
        {
            "text_jp": "八を飲みます。",
            "furigana": "はちをのみます。",
            "romaji": "Hachi o nomimasu.",
            "translation": "Bebo el ocho.",
            "is_correct": False,
        },
        {
            "text_jp": "八が来ました。",
            "furigana": "はちがきました。",
            "romaji": "Hachi ga kimashita.",
            "translation": "El ocho vino.",
            "is_correct": False,
        },
        {
            "text_jp": "八は赤いです。",
            "furigana": "はちはあかいです。",
            "romaji": "Hachi wa akai desu.",
            "translation": "El ocho es rojo.",
            "is_correct": False,
        },
    ],
    "九": [
        {
            "text_jp": "九を食べました。",
            "furigana": "きゅうをたべました。",
            "romaji": "Kyū o tabemashita.",
            "translation": "Comí el nueve.",
            "is_correct": False,
        },
        {
            "text_jp": "九が話します。",
            "furigana": "きゅうがはなします。",
            "romaji": "Kyū ga hanashimasu.",
            "translation": "El nueve habla.",
            "is_correct": False,
        },
        {
            "text_jp": "九は白いです。",
            "furigana": "きゅうはしろいです。",
            "romaji": "Kyū wa shiroi desu.",
            "translation": "El nueve es blanco.",
            "is_correct": False,
        },
    ],
    "十": [
        {
            "text_jp": "十を飲みます。",
            "furigana": "じゅうをのみます。",
            "romaji": "Jū o nomimasu.",
            "translation": "Bebo el diez.",
            "is_correct": False,
        },
        {
            "text_jp": "十が学校に来ます。",
            "furigana": "じゅうががっこうにきます。",
            "romaji": "Jū ga gakkō ni kimasu.",
            "translation": "El diez viene a la escuela.",
            "is_correct": False,
        },
        {
            "text_jp": "十はあまいです。",
            "furigana": "じゅうはあまいです。",
            "romaji": "Jū wa amai desu.",
            "translation": "El diez es dulce.",
            "is_correct": False,
        },
    ],
    "百": [
        {
            "text_jp": "百を食べます。",
            "furigana": "ひゃくをたべます。",
            "romaji": "Hyaku o tabemasu.",
            "translation": "Como el cien.",
            "is_correct": False,
        },
        {
            "text_jp": "百が走ります。",
            "furigana": "ひゃくがはしります。",
            "romaji": "Hyaku ga hashirimasu.",
            "translation": "El cien corre.",
            "is_correct": False,
        },
        {
            "text_jp": "百は青いです。",
            "furigana": "ひゃくはあおいです。",
            "romaji": "Hyaku wa aoi desu.",
            "translation": "El cien es azul.",
            "is_correct": False,
        },
    ],
    "千": [
        {
            "text_jp": "千を飲みました。",
            "furigana": "せんをのみました。",
            "romaji": "Sen o nomimashita.",
            "translation": "Bebí el mil.",
            "is_correct": False,
        },
        {
            "text_jp": "千が話します。",
            "furigana": "せんがはなします。",
            "romaji": "Sen ga hanashimasu.",
            "translation": "El mil habla.",
            "is_correct": False,
        },
        {
            "text_jp": "千はおいしいです。",
            "furigana": "せんはおいしいです。",
            "romaji": "Sen wa oishii desu.",
            "translation": "El mil es delicioso.",
            "is_correct": False,
        },
    ],
    "万": [
        {
            "text_jp": "万を食べます。",
            "furigana": "まんをたべます。",
            "romaji": "Man o tabemasu.",
            "translation": "Como el diez mil.",
            "is_correct": False,
        },
        {
            "text_jp": "万が来ました。",
            "furigana": "まんがきました。",
            "romaji": "Man ga kimashita.",
            "translation": "El diez mil vino.",
            "is_correct": False,
        },
        {
            "text_jp": "万は赤いです。",
            "furigana": "まんはあかいです。",
            "romaji": "Man wa akai desu.",
            "translation": "El diez mil es rojo.",
            "is_correct": False,
        },
    ],
    "円": [
        {
            "text_jp": "円を食べます。",
            "furigana": "えんをたべます。",
            "romaji": "En o tabemasu.",
            "translation": "Como el yen.",
            "is_correct": False,
        },
        {
            "text_jp": "円が走ります。",
            "furigana": "えんがはしります。",
            "romaji": "En ga hashirimasu.",
            "translation": "El yen corre.",
            "is_correct": False,
        },
        {
            "text_jp": "円はおいしいです。",
            "furigana": "えんはおいしいです。",
            "romaji": "En wa oishii desu.",
            "translation": "El yen es delicioso.",
            "is_correct": False,
        },
    ],
    "年": [
        {
            "text_jp": "年を飲みます。",
            "furigana": "としをのみます。",
            "romaji": "Toshi o nomimasu.",
            "translation": "Bebo el año.",
            "is_correct": False,
        },
        {
            "text_jp": "年を食べました。",
            "furigana": "としをたべました。",
            "romaji": "Toshi o tabemashita.",
            "translation": "Comí el año.",
            "is_correct": False,
        },
        {
            "text_jp": "年が走ります。",
            "furigana": "としがはしります。",
            "romaji": "Toshi ga hashirimasu.",
            "translation": "El año corre.",
            "is_correct": False,
        },
    ],
    "月": [
        {
            "text_jp": "月を飲みます。",
            "furigana": "つきをのみます。",
            "romaji": "Tsuki o nomimasu.",
            "translation": "Bebo la luna.",
            "is_correct": False,
        },
        {
            "text_jp": "月を食べました。",
            "furigana": "つきをたべました。",
            "romaji": "Tsuki o tabemashita.",
            "translation": "Comí la luna.",
            "is_correct": False,
        },
        {
            "text_jp": "月が学校に来ます。",
            "furigana": "つきががっこうにきます。",
            "romaji": "Tsuki ga gakkō ni kimasu.",
            "translation": "La luna viene a la escuela.",
            "is_correct": False,
        },
    ],
    "日": [
        {
            "text_jp": "日を飲みます。",
            "furigana": "ひをのみます。",
            "romaji": "Hi o nomimasu.",
            "translation": "Bebo el sol.",
            "is_correct": False,
        },
        {
            "text_jp": "日を食べました。",
            "furigana": "ひをたべました。",
            "romaji": "Hi o tabemashita.",
            "translation": "Comí el sol.",
            "is_correct": False,
        },
        {
            "text_jp": "日が話します。",
            "furigana": "ひがはなします。",
            "romaji": "Hi ga hanashimasu.",
            "translation": "El sol habla.",
            "is_correct": False,
        },
    ],
    "時": [
        {
            "text_jp": "時を食べます。",
            "furigana": "ときをたべます。",
            "romaji": "Toki o tabemasu.",
            "translation": "Como la hora.",
            "is_correct": False,
        },
        {
            "text_jp": "時を飲みました。",
            "furigana": "ときをのみました。",
            "romaji": "Toki o nomimashita.",
            "translation": "Bebí la hora.",
            "is_correct": False,
        },
        {
            "text_jp": "時が走ります。",
            "furigana": "ときがはしります。",
            "romaji": "Toki ga hashirimasu.",
            "translation": "La hora corre.",
            "is_correct": False,
        },
    ],
    "分": [
        {
            "text_jp": "分を食べます。",
            "furigana": "ふんをたべます。",
            "romaji": "Fun o tabemasu.",
            "translation": "Como el minuto.",
            "is_correct": False,
        },
        {
            "text_jp": "分を飲みます。",
            "furigana": "ふんをのみます。",
            "romaji": "Fun o nomimasu.",
            "translation": "Bebo el minuto.",
            "is_correct": False,
        },
        {
            "text_jp": "分が青いです。",
            "furigana": "ふんがあおいです。",
            "romaji": "Fun ga aoi desu.",
            "translation": "El minuto es azul.",
            "is_correct": False,
        },
    ],
    "半": [
        {
            "text_jp": "半を食べました。",
            "furigana": "はんをたべました。",
            "romaji": "Han o tabemashita.",
            "translation": "Comí la mitad.",
            "is_correct": False,
        },
        {
            "text_jp": "半を飲みます。",
            "furigana": "はんをのみます。",
            "romaji": "Han o nomimasu.",
            "translation": "Bebo la mitad.",
            "is_correct": False,
        },
        {
            "text_jp": "半が来ました。",
            "furigana": "はんがきました。",
            "romaji": "Han ga kimashita.",
            "translation": "La mitad vino.",
            "is_correct": False,
        },
    ],
    "今": [
        {
            "text_jp": "今を食べます。",
            "furigana": "いまをたべます。",
            "romaji": "Ima o tabemasu.",
            "translation": "Como el ahora.",
            "is_correct": False,
        },
        {
            "text_jp": "今を飲みました。",
            "furigana": "いまをのみました。",
            "romaji": "Ima o nomimashita.",
            "translation": "Bebí el ahora.",
            "is_correct": False,
        },
        {
            "text_jp": "今が赤いです。",
            "furigana": "いまがあかいです。",
            "romaji": "Ima ga akai desu.",
            "translation": "El ahora es rojo.",
            "is_correct": False,
        },
    ],
    "何": [
        {
            "text_jp": "何はあかいです。",
            "furigana": "なにはあかいです。",
            "romaji": "Nani wa akai desu.",
            "translation": "El qué es rojo.",
            "is_correct": False,
        },
        {
            "text_jp": "何は学校にいます。",
            "furigana": "なにはがっこうにいます。",
            "romaji": "Nani wa gakkō ni imasu.",
            "translation": "El qué está en la escuela.",
            "is_correct": False,
        },
        {
            "text_jp": "何はおいしいです。",
            "furigana": "なにはおいしいです。",
            "romaji": "Nani wa oishii desu.",
            "translation": "El qué es delicioso.",
            "is_correct": False,
        },
    ],
    "毎": [
        {
            "text_jp": "毎日を飲みます。",
            "furigana": "まいにちをのみます。",
            "romaji": "Mainichi o nomimasu.",
            "translation": "Bebo el cada día.",
            "is_correct": False,
        },
        {
            "text_jp": "毎日を食べました。",
            "furigana": "まいにちをたべました。",
            "romaji": "Mainichi o tabemashita.",
            "translation": "Comí el cada día.",
            "is_correct": False,
        },
        {
            "text_jp": "毎日が赤いです。",
            "furigana": "まいにちがあかいです。",
            "romaji": "Mainichi ga akai desu.",
            "translation": "El cada día es rojo.",
            "is_correct": False,
        },
    ],
    "上": [
        {
            "text_jp": "上を飲みます。",
            "furigana": "うえをのみます。",
            "romaji": "Ue o nomimasu.",
            "translation": "Bebo el arriba.",
            "is_correct": False,
        },
        {
            "text_jp": "上を食べました。",
            "furigana": "うえをたべました。",
            "romaji": "Ue o tabemashita.",
            "translation": "Comí el arriba.",
            "is_correct": False,
        },
        {
            "text_jp": "上が話します。",
            "furigana": "うえがはなします。",
            "romaji": "Ue ga hanashimasu.",
            "translation": "El arriba habla.",
            "is_correct": False,
        },
    ],
    "下": [
        {
            "text_jp": "下を食べます。",
            "furigana": "したをたべます。",
            "romaji": "Shita o tabemasu.",
            "translation": "Como el abajo.",
            "is_correct": False,
        },
        {
            "text_jp": "下を飲みました。",
            "furigana": "したをのみました。",
            "romaji": "Shita o nomimashita.",
            "translation": "Bebí el abajo.",
            "is_correct": False,
        },
        {
            "text_jp": "下が来ました。",
            "furigana": "したがきました。",
            "romaji": "Shita ga kimashita.",
            "translation": "El abajo vino.",
            "is_correct": False,
        },
    ],
    "中": [
        {
            "text_jp": "中を飲みます。",
            "furigana": "なかをのみます。",
            "romaji": "Naka o nomimasu.",
            "translation": "Bebo el dentro.",
            "is_correct": False,
        },
        {
            "text_jp": "中を食べました。",
            "furigana": "なかをたべました。",
            "romaji": "Naka o tabemashita.",
            "translation": "Comí el dentro.",
            "is_correct": False,
        },
        {
            "text_jp": "中が話します。",
            "furigana": "なかがはなします。",
            "romaji": "Naka ga hanashimasu.",
            "translation": "El dentro habla.",
            "is_correct": False,
        },
    ],
    "前": [
        {
            "text_jp": "前を食べます。",
            "furigana": "まえをたべます。",
            "romaji": "Mae o tabemasu.",
            "translation": "Como el delante.",
            "is_correct": False,
        },
        {
            "text_jp": "前を飲みました。",
            "furigana": "まえをのみました。",
            "romaji": "Mae o nomimashita.",
            "translation": "Bebí el delante.",
            "is_correct": False,
        },
        {
            "text_jp": "前がおいしいです。",
            "furigana": "まえがおいしいです。",
            "romaji": "Mae ga oishii desu.",
            "translation": "El delante es delicioso.",
            "is_correct": False,
        },
    ],
    "後": [
        {
            "text_jp": "後を飲みます。",
            "furigana": "あとをのみます。",
            "romaji": "Ato o nomimasu.",
            "translation": "Bebo el después.",
            "is_correct": False,
        },
        {
            "text_jp": "後を食べました。",
            "furigana": "あとをたべました。",
            "romaji": "Ato o tabemashita.",
            "translation": "Comí el después.",
            "is_correct": False,
        },
        {
            "text_jp": "後ろが話します。",
            "furigana": "うしろがはなします。",
            "romaji": "Ushiro ga hanashimasu.",
            "translation": "El detrás habla.",
            "is_correct": False,
        },
    ],
    "左": [
        {
            "text_jp": "左を飲みます。",
            "furigana": "ひだりをのみます。",
            "romaji": "Hidari o nomimasu.",
            "translation": "Bebo la izquierda.",
            "is_correct": False,
        },
        {
            "text_jp": "左を食べました。",
            "furigana": "ひだりをたべました。",
            "romaji": "Hidari o tabemashita.",
            "translation": "Comí la izquierda.",
            "is_correct": False,
        },
        {
            "text_jp": "左がおいしいです。",
            "furigana": "ひだりがおいしいです。",
            "romaji": "Hidari ga oishii desu.",
            "translation": "La izquierda es deliciosa.",
            "is_correct": False,
        },
    ],
    "右": [
        {
            "text_jp": "右を食べます。",
            "furigana": "みぎをたべます。",
            "romaji": "Migi o tabemasu.",
            "translation": "Como la derecha.",
            "is_correct": False,
        },
        {
            "text_jp": "右を飲みました。",
            "furigana": "みぎをのみました。",
            "romaji": "Migi o nomimashita.",
            "translation": "Bebí la derecha.",
            "is_correct": False,
        },
        {
            "text_jp": "右が話します。",
            "furigana": "みぎがはなします。",
            "romaji": "Migi ga hanashimasu.",
            "translation": "La derecha habla.",
            "is_correct": False,
        },
    ],
    "人": [
        {
            "text_jp": "人を飲みます。",
            "furigana": "ひとをのみます。",
            "romaji": "Hito o nomimasu.",
            "translation": "Bebo a la persona.",
            "is_correct": False,
        },
        {
            "text_jp": "人を食べます。",
            "furigana": "ひとをたべます。",
            "romaji": "Hito o tabemasu.",
            "translation": "Como a la persona.",
            "is_correct": False,
        },
        {
            "text_jp": "人が雨です。",
            "furigana": "ひとがあめです。",
            "romaji": "Hito ga ame desu.",
            "translation": "La persona es lluvia.",
            "is_correct": False,
        },
    ],
    "名": [
        {
            "text_jp": "名前を飲みます。",
            "furigana": "なまえをのみます。",
            "romaji": "Namae o nomimasu.",
            "translation": "Bebo el nombre.",
            "is_correct": False,
        },
        {
            "text_jp": "名前を食べました。",
            "furigana": "なまえをたべました。",
            "romaji": "Namae o tabemashita.",
            "translation": "Comí el nombre.",
            "is_correct": False,
        },
        {
            "text_jp": "名前が走ります。",
            "furigana": "なまえがはしります。",
            "romaji": "Namae ga hashirimasu.",
            "translation": "El nombre corre.",
            "is_correct": False,
        },
    ],
    "女": [
        {
            "text_jp": "女を飲みます。",
            "furigana": "おんなをのみます。",
            "romaji": "Onna o nomimasu.",
            "translation": "Bebo a la mujer.",
            "is_correct": False,
        },
        {
            "text_jp": "女を食べました。",
            "furigana": "おんなをたべました。",
            "romaji": "Onna o tabemashita.",
            "translation": "Comí a la mujer.",
            "is_correct": False,
        },
        {
            "text_jp": "女が雨です。",
            "furigana": "おんながあめです。",
            "romaji": "Onna ga ame desu.",
            "translation": "La mujer es lluvia.",
            "is_correct": False,
        },
    ],
    "男": [
        {
            "text_jp": "男を食べます。",
            "furigana": "おとこをたべます。",
            "romaji": "Otoko o tabemasu.",
            "translation": "Como al hombre.",
            "is_correct": False,
        },
        {
            "text_jp": "男を飲みました。",
            "furigana": "おとこをのみました。",
            "romaji": "Otoko o nomimashita.",
            "translation": "Bebí al hombre.",
            "is_correct": False,
        },
        {
            "text_jp": "男が空です。",
            "furigana": "おとこがそらです。",
            "romaji": "Otoko ga sora desu.",
            "translation": "El hombre es cielo.",
            "is_correct": False,
        },
    ],
    "子": [
        {
            "text_jp": "子を飲みます。",
            "furigana": "こをのみます。",
            "romaji": "Ko o nomimasu.",
            "translation": "Bebo al niño.",
            "is_correct": False,
        },
        {
            "text_jp": "子を食べました。",
            "furigana": "こをたべました。",
            "romaji": "Ko o tabemashita.",
            "translation": "Comí al niño.",
            "is_correct": False,
        },
        {
            "text_jp": "子が石です。",
            "furigana": "こがいしです。",
            "romaji": "Ko ga ishi desu.",
            "translation": "El niño es piedra.",
            "is_correct": False,
        },
    ],
    "父": [
        {
            "text_jp": "父を飲みます。",
            "furigana": "ちちをのみます。",
            "romaji": "Chichi o nomimasu.",
            "translation": "Bebo a mi padre.",
            "is_correct": False,
        },
        {
            "text_jp": "父を食べました。",
            "furigana": "ちちをたべました。",
            "romaji": "Chichi o tabemashita.",
            "translation": "Comí a mi padre.",
            "is_correct": False,
        },
        {
            "text_jp": "父が花です。",
            "furigana": "ちちがはなです。",
            "romaji": "Chichi ga hana desu.",
            "translation": "Mi padre es flor.",
            "is_correct": False,
        },
    ],
    "母": [
        {
            "text_jp": "母を食べます。",
            "furigana": "ははをたべます。",
            "romaji": "Haha o tabemasu.",
            "translation": "Como a mi madre.",
            "is_correct": False,
        },
        {
            "text_jp": "母を飲みました。",
            "furigana": "ははをのみました。",
            "romaji": "Haha o nomimashita.",
            "translation": "Bebí a mi madre.",
            "is_correct": False,
        },
        {
            "text_jp": "母が車です。",
            "furigana": "ははがくるまです。",
            "romaji": "Haha ga kuruma desu.",
            "translation": "Mi madre es coche.",
            "is_correct": False,
        },
    ],
    "兄": [
        {
            "text_jp": "兄を飲みます。",
            "furigana": "あにをのみます。",
            "romaji": "Ani o nomimasu.",
            "translation": "Bebo a mi hermano mayor.",
            "is_correct": False,
        },
        {
            "text_jp": "兄を食べました。",
            "furigana": "あにをたべました。",
            "romaji": "Ani o tabemashita.",
            "translation": "Comí a mi hermano mayor.",
            "is_correct": False,
        },
        {
            "text_jp": "兄が水です。",
            "furigana": "あにがみずです。",
            "romaji": "Ani ga mizu desu.",
            "translation": "Mi hermano mayor es agua.",
            "is_correct": False,
        },
    ],
    "弟": [
        {
            "text_jp": "弟を食べます。",
            "furigana": "おとうとをたべます。",
            "romaji": "Otōto o tabemasu.",
            "translation": "Como a mi hermano menor.",
            "is_correct": False,
        },
        {
            "text_jp": "弟を飲みました。",
            "furigana": "おとうとをのみました。",
            "romaji": "Otōto o nomimashita.",
            "translation": "Bebí a mi hermano menor.",
            "is_correct": False,
        },
        {
            "text_jp": "弟が山です。",
            "furigana": "おとうとがやまです。",
            "romaji": "Otōto ga yama desu.",
            "translation": "Mi hermano menor es montaña.",
            "is_correct": False,
        },
    ],
    "姉": [
        {
            "text_jp": "姉を飲みます。",
            "furigana": "あねをのみます。",
            "romaji": "Ane o nomimasu.",
            "translation": "Bebo a mi hermana mayor.",
            "is_correct": False,
        },
        {
            "text_jp": "姉を食べました。",
            "furigana": "あねをたべました。",
            "romaji": "Ane o tabemashita.",
            "translation": "Comí a mi hermana mayor.",
            "is_correct": False,
        },
        {
            "text_jp": "姉が雨です。",
            "furigana": "あねがあめです。",
            "romaji": "Ane ga ame desu.",
            "translation": "Mi hermana mayor es lluvia.",
            "is_correct": False,
        },
    ],
    "妹": [
        {
            "text_jp": "妹を食べます。",
            "furigana": "いもうとをたべます。",
            "romaji": "Imōto o tabemasu.",
            "translation": "Como a mi hermana menor.",
            "is_correct": False,
        },
        {
            "text_jp": "妹を飲みました。",
            "furigana": "いもうとをのみました。",
            "romaji": "Imōto o nomimashita.",
            "translation": "Bebí a mi hermana menor.",
            "is_correct": False,
        },
        {
            "text_jp": "妹が木です。",
            "furigana": "いもうとがきです。",
            "romaji": "Imōto ga ki desu.",
            "translation": "Mi hermana menor es árbol.",
            "is_correct": False,
        },
    ],
    "友": [
        {
            "text_jp": "友だちを飲みます。",
            "furigana": "ともだちをのみます。",
            "romaji": "Tomodachi o nomimasu.",
            "translation": "Bebo a mi amigo.",
            "is_correct": False,
        },
        {
            "text_jp": "友だちを食べました。",
            "furigana": "ともだちをたべました。",
            "romaji": "Tomodachi o tabemashita.",
            "translation": "Comí a mi amigo.",
            "is_correct": False,
        },
        {
            "text_jp": "友だちが石です。",
            "furigana": "ともだちがいしです。",
            "romaji": "Tomodachi ga ishi desu.",
            "translation": "Mi amigo es piedra.",
            "is_correct": False,
        },
    ],
    "先": [
        {
            "text_jp": "先生を飲みます。",
            "furigana": "せんせいをのみます。",
            "romaji": "Sensei o nomimasu.",
            "translation": "Bebo al profesor.",
            "is_correct": False,
        },
        {
            "text_jp": "先生を食べました。",
            "furigana": "せんせいをたべました。",
            "romaji": "Sensei o tabemashita.",
            "translation": "Comí al profesor.",
            "is_correct": False,
        },
        {
            "text_jp": "先生が川です。",
            "furigana": "せんせいがかわです。",
            "romaji": "Sensei ga kawa desu.",
            "translation": "El profesor es río.",
            "is_correct": False,
        },
    ],
    "生": [
        {
            "text_jp": "学生を飲みます。",
            "furigana": "がくせいをのみます。",
            "romaji": "Gakusei o nomimasu.",
            "translation": "Bebo al estudiante.",
            "is_correct": False,
        },
        {
            "text_jp": "学生を食べました。",
            "furigana": "がくせいをたべました。",
            "romaji": "Gakusei o tabemashita.",
            "translation": "Comí al estudiante.",
            "is_correct": False,
        },
        {
            "text_jp": "学生が空です。",
            "furigana": "がくせいがそらです。",
            "romaji": "Gakusei ga sora desu.",
            "translation": "El estudiante es cielo.",
            "is_correct": False,
        },
    ],
    "目": [
        {
            "text_jp": "目でごはんを食べます。",
            "furigana": "めでごはんをたべます。",
            "romaji": "Me de gohan o tabemasu.",
            "translation": "Como arroz con el ojo.",
            "is_correct": False,
        },
        {
            "text_jp": "目で水を飲みます。",
            "furigana": "めでみずをのみます。",
            "romaji": "Me de mizu o nomimasu.",
            "translation": "Bebo agua con el ojo.",
            "is_correct": False,
        },
        {
            "text_jp": "目で話します。",
            "furigana": "めではなします。",
            "romaji": "Me de hanashimasu.",
            "translation": "Hablo con el ojo.",
            "is_correct": False,
        },
    ],
    "口": [
        {
            "text_jp": "口で見ます。",
            "furigana": "くちでみます。",
            "romaji": "Kuchi de mimasu.",
            "translation": "Veo con la boca.",
            "is_correct": False,
        },
        {
            "text_jp": "口で音楽を聞きます。",
            "furigana": "くちでおんがくをききます。",
            "romaji": "Kuchi de ongaku o kikimasu.",
            "translation": "Escucho música con la boca.",
            "is_correct": False,
        },
        {
            "text_jp": "口で歩きます。",
            "furigana": "くちであるきます。",
            "romaji": "Kuchi de arukimasu.",
            "translation": "Camino con la boca.",
            "is_correct": False,
        },
    ],
    "耳": [
        {
            "text_jp": "耳で映画を見ます。",
            "furigana": "みみでえいがをみます。",
            "romaji": "Mimi de eiga o mimasu.",
            "translation": "Veo una película con la oreja.",
            "is_correct": False,
        },
        {
            "text_jp": "耳でごはんを食べます。",
            "furigana": "みみでごはんをたべます。",
            "romaji": "Mimi de gohan o tabemasu.",
            "translation": "Como arroz con la oreja.",
            "is_correct": False,
        },
        {
            "text_jp": "耳で字を書きます。",
            "furigana": "みみでじをかきます。",
            "romaji": "Mimi de ji o kakimasu.",
            "translation": "Escribo letras con la oreja.",
            "is_correct": False,
        },
    ],
    "手": [
        {
            "text_jp": "手で音楽を聞きます。",
            "furigana": "てでおんがくをききます。",
            "romaji": "Te de ongaku o kikimasu.",
            "translation": "Escucho música con la mano.",
            "is_correct": False,
        },
        {
            "text_jp": "手で見ます。",
            "furigana": "てでみます。",
            "romaji": "Te de mimasu.",
            "translation": "Veo con la mano.",
            "is_correct": False,
        },
        {
            "text_jp": "手を飲みます。",
            "furigana": "てをのみます。",
            "romaji": "Te o nomimasu.",
            "translation": "Bebo la mano.",
            "is_correct": False,
        },
    ],
    "足": [
        {
            "text_jp": "足で本を読みます。",
            "furigana": "あしでほんをよみます。",
            "romaji": "Ashi de hon o yomimasu.",
            "translation": "Leo un libro con el pie.",
            "is_correct": False,
        },
        {
            "text_jp": "足でごはんを食べます。",
            "furigana": "あしでごはんをたべます。",
            "romaji": "Ashi de gohan o tabemasu.",
            "translation": "Como arroz con el pie.",
            "is_correct": False,
        },
        {
            "text_jp": "足で話します。",
            "furigana": "あしではなします。",
            "romaji": "Ashi de hanashimasu.",
            "translation": "Hablo con el pie.",
            "is_correct": False,
        },
    ],
    "山": [
        {
            "text_jp": "山を飲みます。",
            "furigana": "やまをのみます。",
            "romaji": "Yama o nomimasu.",
            "translation": "Bebo la montaña.",
            "is_correct": False,
        },
        {
            "text_jp": "山を読みます。",
            "furigana": "やまをよみます。",
            "romaji": "Yama o yomimasu.",
            "translation": "Leo la montaña.",
            "is_correct": False,
        },
        {
            "text_jp": "山が来ました。",
            "furigana": "やまがきました。",
            "romaji": "Yama ga kimashita.",
            "translation": "La montaña vino.",
            "is_correct": False,
        },
    ],
    "川": [
        {
            "text_jp": "川を食べます。",
            "furigana": "かわをたべます。",
            "romaji": "Kawa o tabemasu.",
            "translation": "Como el río.",
            "is_correct": False,
        },
        {
            "text_jp": "川を読みました。",
            "furigana": "かわをよみました。",
            "romaji": "Kawa o yomimashita.",
            "translation": "Leí el río.",
            "is_correct": False,
        },
        {
            "text_jp": "川が話します。",
            "furigana": "かわがはなします。",
            "romaji": "Kawa ga hanashimasu.",
            "translation": "El río habla.",
            "is_correct": False,
        },
    ],
    "田": [
        {
            "text_jp": "田を飲みます。",
            "furigana": "たをのみます。",
            "romaji": "Ta o nomimasu.",
            "translation": "Bebo el arrozal.",
            "is_correct": False,
        },
        {
            "text_jp": "田を食べました。",
            "furigana": "たをたべました。",
            "romaji": "Ta o tabemashita.",
            "translation": "Comí el arrozal.",
            "is_correct": False,
        },
        {
            "text_jp": "田が走ります。",
            "furigana": "たがはしります。",
            "romaji": "Ta ga hashirimasu.",
            "translation": "El arrozal corre.",
            "is_correct": False,
        },
    ],
    "石": [
        {
            "text_jp": "石を飲みます。",
            "furigana": "いしをのみます。",
            "romaji": "Ishi o nomimasu.",
            "translation": "Bebo la piedra.",
            "is_correct": False,
        },
        {
            "text_jp": "石が話します。",
            "furigana": "いしがはなします。",
            "romaji": "Ishi ga hanashimasu.",
            "translation": "La piedra habla.",
            "is_correct": False,
        },
        {
            "text_jp": "石はおいしいです。",
            "furigana": "いしはおいしいです。",
            "romaji": "Ishi wa oishii desu.",
            "translation": "La piedra es deliciosa.",
            "is_correct": False,
        },
    ],
    "花": [
        {
            "text_jp": "花を飲みます。",
            "furigana": "はなをのみます。",
            "romaji": "Hana o nomimasu.",
            "translation": "Bebo la flor.",
            "is_correct": False,
        },
        {
            "text_jp": "花が行きます。",
            "furigana": "はながいきます。",
            "romaji": "Hana ga ikimasu.",
            "translation": "La flor va.",
            "is_correct": False,
        },
        {
            "text_jp": "花を読みました。",
            "furigana": "はなをよみました。",
            "romaji": "Hana o yomimashita.",
            "translation": "Leí la flor.",
            "is_correct": False,
        },
    ],
    "草": [
        {
            "text_jp": "草を飲みます。",
            "furigana": "くさをのみます。",
            "romaji": "Kusa o nomimasu.",
            "translation": "Bebo la hierba.",
            "is_correct": False,
        },
        {
            "text_jp": "草が話します。",
            "furigana": "くさがはなします。",
            "romaji": "Kusa ga hanashimasu.",
            "translation": "La hierba habla.",
            "is_correct": False,
        },
        {
            "text_jp": "草を読みます。",
            "furigana": "くさをよみます。",
            "romaji": "Kusa o yomimasu.",
            "translation": "Leo la hierba.",
            "is_correct": False,
        },
    ],
    "木": [
        {
            "text_jp": "木を飲みます。",
            "furigana": "きをのみます。",
            "romaji": "Ki o nomimasu.",
            "translation": "Bebo el árbol.",
            "is_correct": False,
        },
        {
            "text_jp": "木が来ました。",
            "furigana": "きがきました。",
            "romaji": "Ki ga kimashita.",
            "translation": "El árbol vino.",
            "is_correct": False,
        },
        {
            "text_jp": "木を読みました。",
            "furigana": "きをよみました。",
            "romaji": "Ki o yomimashita.",
            "translation": "Leí el árbol.",
            "is_correct": False,
        },
    ],
    "林": [
        {
            "text_jp": "林を食べます。",
            "furigana": "はやしをたべます。",
            "romaji": "Hayashi o tabemasu.",
            "translation": "Como el bosquecillo.",
            "is_correct": False,
        },
        {
            "text_jp": "林を飲みました。",
            "furigana": "はやしをのみました。",
            "romaji": "Hayashi o nomimashita.",
            "translation": "Bebí el bosquecillo.",
            "is_correct": False,
        },
        {
            "text_jp": "林が話します。",
            "furigana": "はやしがはなします。",
            "romaji": "Hayashi ga hanashimasu.",
            "translation": "El bosquecillo habla.",
            "is_correct": False,
        },
    ],
    "森": [
        {
            "text_jp": "森を飲みます。",
            "furigana": "もりをのみます。",
            "romaji": "Mori o nomimasu.",
            "translation": "Bebo el bosque.",
            "is_correct": False,
        },
        {
            "text_jp": "森を読みました。",
            "furigana": "もりをよみました。",
            "romaji": "Mori o yomimashita.",
            "translation": "Leí el bosque.",
            "is_correct": False,
        },
        {
            "text_jp": "森が走ります。",
            "furigana": "もりがはしります。",
            "romaji": "Mori ga hashirimasu.",
            "translation": "El bosque corre.",
            "is_correct": False,
        },
    ],
    "火": [
        {
            "text_jp": "火を飲みます。",
            "furigana": "ひをのみます。",
            "romaji": "Hi o nomimasu.",
            "translation": "Bebo el fuego.",
            "is_correct": False,
        },
        {
            "text_jp": "火はつめたいです。",
            "furigana": "ひはつめたいです。",
            "romaji": "Hi wa tsumetai desu.",
            "translation": "El fuego es frío.",
            "is_correct": False,
        },
        {
            "text_jp": "火を読みます。",
            "furigana": "ひをよみます。",
            "romaji": "Hi o yomimasu.",
            "translation": "Leo el fuego.",
            "is_correct": False,
        },
    ],
    "水": [
        {
            "text_jp": "水を食べます。",
            "furigana": "みずをたべます。",
            "romaji": "Mizu o tabemasu.",
            "translation": "Como el agua.",
            "is_correct": False,
        },
        {
            "text_jp": "水で本を書きます。",
            "furigana": "みずでほんをかきます。",
            "romaji": "Mizu de hon o kakimasu.",
            "translation": "Escribo un libro con agua.",
            "is_correct": False,
        },
        {
            "text_jp": "水を読みました。",
            "furigana": "みずをよみました。",
            "romaji": "Mizu o yomimashita.",
            "translation": "Leí el agua.",
            "is_correct": False,
        },
    ],
    "土": [
        {
            "text_jp": "土を飲みます。",
            "furigana": "つちをのみます。",
            "romaji": "Tsuchi o nomimasu.",
            "translation": "Bebo la tierra.",
            "is_correct": False,
        },
        {
            "text_jp": "土を読みました。",
            "furigana": "つちをよみました。",
            "romaji": "Tsuchi o yomimashita.",
            "translation": "Leí la tierra.",
            "is_correct": False,
        },
        {
            "text_jp": "土が話します。",
            "furigana": "つちがはなします。",
            "romaji": "Tsuchi ga hanashimasu.",
            "translation": "La tierra habla.",
            "is_correct": False,
        },
    ],
    "気": [
        {
            "text_jp": "天気を食べます。",
            "furigana": "てんきをたべます。",
            "romaji": "Tenki o tabemasu.",
            "translation": "Como el clima.",
            "is_correct": False,
        },
        {
            "text_jp": "天気を飲みました。",
            "furigana": "てんきをのみました。",
            "romaji": "Tenki o nomimashita.",
            "translation": "Bebí el clima.",
            "is_correct": False,
        },
        {
            "text_jp": "天気を読みます。",
            "furigana": "てんきをよみます。",
            "romaji": "Tenki o yomimasu.",
            "translation": "Leo el clima.",
            "is_correct": False,
        },
    ],
    "空": [
        {
            "text_jp": "空を飲みます。",
            "furigana": "そらをのみます。",
            "romaji": "Sora o nomimasu.",
            "translation": "Bebo el cielo.",
            "is_correct": False,
        },
        {
            "text_jp": "空を食べました。",
            "furigana": "そらをたべました。",
            "romaji": "Sora o tabemashita.",
            "translation": "Comí el cielo.",
            "is_correct": False,
        },
        {
            "text_jp": "空が走ります。",
            "furigana": "そらがはしります。",
            "romaji": "Sora ga hashirimasu.",
            "translation": "El cielo corre.",
            "is_correct": False,
        },
    ],
    "雨": [
        {
            "text_jp": "雨を食べます。",
            "furigana": "あめをたべます。",
            "romaji": "Ame o tabemasu.",
            "translation": "Como la lluvia.",
            "is_correct": False,
        },
        {
            "text_jp": "雨を読みました。",
            "furigana": "あめをよみました。",
            "romaji": "Ame o yomimashita.",
            "translation": "Leí la lluvia.",
            "is_correct": False,
        },
        {
            "text_jp": "雨が話します。",
            "furigana": "あめがはなします。",
            "romaji": "Ame ga hanashimasu.",
            "translation": "La lluvia habla.",
            "is_correct": False,
        },
    ],
    "天": [
        {
            "text_jp": "天気を買います。",
            "furigana": "てんきをかいます。",
            "romaji": "Tenki o kaimasu.",
            "translation": "Compro el clima.",
            "is_correct": False,
        },
        {
            "text_jp": "天気が歩きます。",
            "furigana": "てんきがあるきます。",
            "romaji": "Tenki ga arukimasu.",
            "translation": "El clima camina.",
            "is_correct": False,
        },
        {
            "text_jp": "天気はあまいです。",
            "furigana": "てんきはあまいです。",
            "romaji": "Tenki wa amai desu.",
            "translation": "El clima es dulce.",
            "is_correct": False,
        },
    ],
    "国": [
        {
            "text_jp": "国を飲みます。",
            "furigana": "くにをのみます。",
            "romaji": "Kuni o nomimasu.",
            "translation": "Bebo el país.",
            "is_correct": False,
        },
        {
            "text_jp": "国を食べました。",
            "furigana": "くにをたべました。",
            "romaji": "Kuni o tabemashita.",
            "translation": "Comí el país.",
            "is_correct": False,
        },
        {
            "text_jp": "国が走ります。",
            "furigana": "くにがはしります。",
            "romaji": "Kuni ga hashirimasu.",
            "translation": "El país corre.",
            "is_correct": False,
        },
    ],
    "語": [
        {
            "text_jp": "日本語を飲みます。",
            "furigana": "にほんごをのみます。",
            "romaji": "Nihongo o nomimasu.",
            "translation": "Bebo el japonés.",
            "is_correct": False,
        },
        {
            "text_jp": "日本語を食べました。",
            "furigana": "にほんごをたべました。",
            "romaji": "Nihongo o tabemashita.",
            "translation": "Comí el japonés.",
            "is_correct": False,
        },
        {
            "text_jp": "日本語が走ります。",
            "furigana": "にほんごがはしります。",
            "romaji": "Nihongo ga hashirimasu.",
            "translation": "El japonés corre.",
            "is_correct": False,
        },
    ],
    "学": [
        {
            "text_jp": "学校を飲みます。",
            "furigana": "がっこうをのみます。",
            "romaji": "Gakkō o nomimasu.",
            "translation": "Bebo la escuela.",
            "is_correct": False,
        },
        {
            "text_jp": "学校を食べました。",
            "furigana": "がっこうをたべました。",
            "romaji": "Gakkō o tabemashita.",
            "translation": "Comí la escuela.",
            "is_correct": False,
        },
        {
            "text_jp": "学校が話します。",
            "furigana": "がっこうがはなします。",
            "romaji": "Gakkō ga hanashimasu.",
            "translation": "La escuela habla.",
            "is_correct": False,
        },
    ],
    "校": [
        {
            "text_jp": "学校を食べます。",
            "furigana": "がっこうをたべます。",
            "romaji": "Gakkō o tabemasu.",
            "translation": "Como la escuela.",
            "is_correct": False,
        },
        {
            "text_jp": "学校を飲みました。",
            "furigana": "がっこうをのみました。",
            "romaji": "Gakkō o nomimashita.",
            "translation": "Bebí la escuela.",
            "is_correct": False,
        },
        {
            "text_jp": "学校がおいしいです。",
            "furigana": "がっこうがおいしいです。",
            "romaji": "Gakkō ga oishii desu.",
            "translation": "La escuela es deliciosa.",
            "is_correct": False,
        },
    ],
    "教": [
        {
            "text_jp": "教室を飲みます。",
            "furigana": "きょうしつをのみます。",
            "romaji": "Kyōshitsu o nomimasu.",
            "translation": "Bebo el aula.",
            "is_correct": False,
        },
        {
            "text_jp": "教室を食べました。",
            "furigana": "きょうしつをたべました。",
            "romaji": "Kyōshitsu o tabemashita.",
            "translation": "Comí el aula.",
            "is_correct": False,
        },
        {
            "text_jp": "教室が走ります。",
            "furigana": "きょうしつがはしります。",
            "romaji": "Kyōshitsu ga hashirimasu.",
            "translation": "El aula corre.",
            "is_correct": False,
        },
    ],
    "書": [
        {
            "text_jp": "水を書きます。",
            "furigana": "みずをかきます。",
            "romaji": "Mizu o kakimasu.",
            "translation": "Escribo el agua.",
            "is_correct": False,
        },
        {
            "text_jp": "山を書きました。",
            "furigana": "やまをかきました。",
            "romaji": "Yama o kakimashita.",
            "translation": "Escribí la montaña.",
            "is_correct": False,
        },
        {
            "text_jp": "ごはんを書きます。",
            "furigana": "ごはんをかきます。",
            "romaji": "Gohan o kakimasu.",
            "translation": "Escribo el arroz.",
            "is_correct": False,
        },
    ],
    "読": [
        {
            "text_jp": "水を読みます。",
            "furigana": "みずをよみます。",
            "romaji": "Mizu o yomimasu.",
            "translation": "Leo el agua.",
            "is_correct": False,
        },
        {
            "text_jp": "ごはんを読みました。",
            "furigana": "ごはんをよみました。",
            "romaji": "Gohan o yomimashita.",
            "translation": "Leí el arroz.",
            "is_correct": False,
        },
        {
            "text_jp": "山を読みます。",
            "furigana": "やまをよみます。",
            "romaji": "Yama o yomimasu.",
            "translation": "Leo la montaña.",
            "is_correct": False,
        },
    ],
    "話": [
        {
            "text_jp": "水を話します。",
            "furigana": "みずをはなします。",
            "romaji": "Mizu o hanashimasu.",
            "translation": "Hablo el agua.",
            "is_correct": False,
        },
        {
            "text_jp": "ごはんを話します。",
            "furigana": "ごはんをはなします。",
            "romaji": "Gohan o hanashimasu.",
            "translation": "Hablo el arroz.",
            "is_correct": False,
        },
        {
            "text_jp": "山が話します。",
            "furigana": "やまがはなします。",
            "romaji": "Yama ga hanashimasu.",
            "translation": "La montaña habla.",
            "is_correct": False,
        },
    ],
    "言": [
        {
            "text_jp": "水を言います。",
            "furigana": "みずをいいます。",
            "romaji": "Mizu o iimasu.",
            "translation": "Digo el agua.",
            "is_correct": False,
        },
        {
            "text_jp": "ごはんを言いました。",
            "furigana": "ごはんをいいました。",
            "romaji": "Gohan o iimashita.",
            "translation": "Dije el arroz.",
            "is_correct": False,
        },
        {
            "text_jp": "石が言います。",
            "furigana": "いしがいいます。",
            "romaji": "Ishi ga iimasu.",
            "translation": "La piedra dice.",
            "is_correct": False,
        },
    ],
    "聞": [
        {
            "text_jp": "目で音楽を聞きます。",
            "furigana": "めでおんがくをききます。",
            "romaji": "Me de ongaku o kikimasu.",
            "translation": "Escucho música con los ojos.",
            "is_correct": False,
        },
        {
            "text_jp": "ごはんを聞きます。",
            "furigana": "ごはんをききます。",
            "romaji": "Gohan o kikimasu.",
            "translation": "Escucho el arroz.",
            "is_correct": False,
        },
        {
            "text_jp": "山を聞きました。",
            "furigana": "やまをききました。",
            "romaji": "Yama o kikimashita.",
            "translation": "Escuché la montaña.",
            "is_correct": False,
        },
    ],
    "行": [
        {
            "text_jp": "本が行きます。",
            "furigana": "ほんがいきます。",
            "romaji": "Hon ga ikimasu.",
            "translation": "El libro va.",
            "is_correct": False,
        },
        {
            "text_jp": "水を行きます。",
            "furigana": "みずをいきます。",
            "romaji": "Mizu o ikimasu.",
            "translation": "Voy el agua.",
            "is_correct": False,
        },
        {
            "text_jp": "石が学校へ行きます。",
            "furigana": "いしががっこうへいきます。",
            "romaji": "Ishi ga gakkō e ikimasu.",
            "translation": "La piedra va a la escuela.",
            "is_correct": False,
        },
    ],
    "来": [
        {
            "text_jp": "山が来ます。",
            "furigana": "やまがきます。",
            "romaji": "Yama ga kimasu.",
            "translation": "La montaña viene.",
            "is_correct": False,
        },
        {
            "text_jp": "本が来ました。",
            "furigana": "ほんがきました。",
            "romaji": "Hon ga kimashita.",
            "translation": "El libro vino.",
            "is_correct": False,
        },
        {
            "text_jp": "石が来ます。",
            "furigana": "いしがきます。",
            "romaji": "Ishi ga kimasu.",
            "translation": "La piedra viene.",
            "is_correct": False,
        },
    ],
    "帰": [
        {
            "text_jp": "本が帰ります。",
            "furigana": "ほんがかえります。",
            "romaji": "Hon ga kaerimasu.",
            "translation": "El libro regresa.",
            "is_correct": False,
        },
        {
            "text_jp": "山が帰りました。",
            "furigana": "やまがかえりました。",
            "romaji": "Yama ga kaerimashita.",
            "translation": "La montaña regresó.",
            "is_correct": False,
        },
        {
            "text_jp": "水が家に帰ります。",
            "furigana": "みずがいえにかえります。",
            "romaji": "Mizu ga ie ni kaerimasu.",
            "translation": "El agua regresa a casa.",
            "is_correct": False,
        },
    ],
    "入": [
        {
            "text_jp": "本が部屋に入ります。",
            "furigana": "ほんがへやにはいります。",
            "romaji": "Hon ga heya ni hairimasu.",
            "translation": "El libro entra en el cuarto.",
            "is_correct": False,
        },
        {
            "text_jp": "水を入ります。",
            "furigana": "みずをはいります。",
            "romaji": "Mizu o hairimasu.",
            "translation": "Entro el agua.",
            "is_correct": False,
        },
        {
            "text_jp": "山が入りました。",
            "furigana": "やまがはいりました。",
            "romaji": "Yama ga hairimashita.",
            "translation": "La montaña entró.",
            "is_correct": False,
        },
    ],
    "出": [
        {
            "text_jp": "本が出ます。",
            "furigana": "ほんがでます。",
            "romaji": "Hon ga demasu.",
            "translation": "El libro sale.",
            "is_correct": False,
        },
        {
            "text_jp": "山が出ました。",
            "furigana": "やまがでました。",
            "romaji": "Yama ga demashita.",
            "translation": "La montaña salió.",
            "is_correct": False,
        },
        {
            "text_jp": "石が家を出ます。",
            "furigana": "いしがいえをでます。",
            "romaji": "Ishi ga ie o demasu.",
            "translation": "La piedra sale de la casa.",
            "is_correct": False,
        },
    ],
    "見": [
        {
            "text_jp": "耳で映画を見ます。",
            "furigana": "みみでえいがをみます。",
            "romaji": "Mimi de eiga o mimasu.",
            "translation": "Veo una película con la oreja.",
            "is_correct": False,
        },
        {
            "text_jp": "音を見ます。",
            "furigana": "おとをみます。",
            "romaji": "Oto o mimasu.",
            "translation": "Veo el sonido.",
            "is_correct": False,
        },
        {
            "text_jp": "音楽を見ました。",
            "furigana": "おんがくをみました。",
            "romaji": "Ongaku o mimashita.",
            "translation": "Vi la música.",
            "is_correct": False,
        },
    ],
    "休": [
        {
            "text_jp": "石が休みます。",
            "furigana": "いしがやすみます。",
            "romaji": "Ishi ga yasumimasu.",
            "translation": "La piedra descansa.",
            "is_correct": False,
        },
        {
            "text_jp": "水を休みます。",
            "furigana": "みずをやすみます。",
            "romaji": "Mizu o yasumimasu.",
            "translation": "Descanso el agua.",
            "is_correct": False,
        },
        {
            "text_jp": "山が休みました。",
            "furigana": "やまがやすみました。",
            "romaji": "Yama ga yasumimashita.",
            "translation": "La montaña descansó.",
            "is_correct": False,
        },
    ],
    "食": [
        {
            "text_jp": "水を食べます。",
            "furigana": "みずをたべます。",
            "romaji": "Mizu o tabemasu.",
            "translation": "Como el agua.",
            "is_correct": False,
        },
        {
            "text_jp": "本を食べました。",
            "furigana": "ほんをたべました。",
            "romaji": "Hon o tabemashita.",
            "translation": "Comí el libro.",
            "is_correct": False,
        },
        {
            "text_jp": "音楽を食べます。",
            "furigana": "おんがくをたべます。",
            "romaji": "Ongaku o tabemasu.",
            "translation": "Como la música.",
            "is_correct": False,
        },
    ],
    "飲": [
        {
            "text_jp": "本を飲みます。",
            "furigana": "ほんをのみます。",
            "romaji": "Hon o nomimasu.",
            "translation": "Bebo el libro.",
            "is_correct": False,
        },
        {
            "text_jp": "ごはんを飲みました。",
            "furigana": "ごはんをのみました。",
            "romaji": "Gohan o nomimashita.",
            "translation": "Bebí el arroz.",
            "is_correct": False,
        },
        {
            "text_jp": "山を飲みます。",
            "furigana": "やまをのみます。",
            "romaji": "Yama o nomimasu.",
            "translation": "Bebo la montaña.",
            "is_correct": False,
        },
    ],
    "買": [
        {
            "text_jp": "空を買います。",
            "furigana": "そらをかいます。",
            "romaji": "Sora o kaimasu.",
            "translation": "Compro el cielo.",
            "is_correct": False,
        },
        {
            "text_jp": "雨を買いました。",
            "furigana": "あめをかいました。",
            "romaji": "Ame o kaimashita.",
            "translation": "Compré la lluvia.",
            "is_correct": False,
        },
        {
            "text_jp": "天気を買います。",
            "furigana": "てんきをかいます。",
            "romaji": "Tenki o kaimasu.",
            "translation": "Compro el clima.",
            "is_correct": False,
        },
    ],
    "本": [
        {
            "text_jp": "本を飲みます。",
            "furigana": "ほんをのみます。",
            "romaji": "Hon o nomimasu.",
            "translation": "Bebo el libro.",
            "is_correct": False,
        },
        {
            "text_jp": "本を食べました。",
            "furigana": "ほんをたべました。",
            "romaji": "Hon o tabemashita.",
            "translation": "Comí el libro.",
            "is_correct": False,
        },
        {
            "text_jp": "本が走ります。",
            "furigana": "ほんがはしります。",
            "romaji": "Hon ga hashirimasu.",
            "translation": "El libro corre.",
            "is_correct": False,
        },
    ],
    "電": [
        {
            "text_jp": "電気を飲みます。",
            "furigana": "でんきをのみます。",
            "romaji": "Denki o nomimasu.",
            "translation": "Bebo la electricidad.",
            "is_correct": False,
        },
        {
            "text_jp": "電気がおいしいです。",
            "furigana": "でんきがおいしいです。",
            "romaji": "Denki ga oishii desu.",
            "translation": "La electricidad es deliciosa.",
            "is_correct": False,
        },
        {
            "text_jp": "電車を食べました。",
            "furigana": "でんしゃをたべました。",
            "romaji": "Densha o tabemashita.",
            "translation": "Comí el tren.",
            "is_correct": False,
        },
    ],
    "車": [
        {
            "text_jp": "車を飲みます。",
            "furigana": "くるまをのみます。",
            "romaji": "Kuruma o nomimasu.",
            "translation": "Bebo el coche.",
            "is_correct": False,
        },
        {
            "text_jp": "車を食べました。",
            "furigana": "くるまをたべました。",
            "romaji": "Kuruma o tabemashita.",
            "translation": "Comí el coche.",
            "is_correct": False,
        },
        {
            "text_jp": "車が話します。",
            "furigana": "くるまがはなします。",
            "romaji": "Kuruma ga hanashimasu.",
            "translation": "El coche habla.",
            "is_correct": False,
        },
    ],
    "駅": [
        {
            "text_jp": "駅を飲みます。",
            "furigana": "えきをのみます。",
            "romaji": "Eki o nomimasu.",
            "translation": "Bebo la estación.",
            "is_correct": False,
        },
        {
            "text_jp": "駅を食べました。",
            "furigana": "えきをたべました。",
            "romaji": "Eki o tabemashita.",
            "translation": "Comí la estación.",
            "is_correct": False,
        },
        {
            "text_jp": "駅が走ります。",
            "furigana": "えきがはしります。",
            "romaji": "Eki ga hashirimasu.",
            "translation": "La estación corre.",
            "is_correct": False,
        },
    ],
    "大": [
        {
            "text_jp": "大きい本を食べます。",
            "furigana": "おおきいほんをたべます。",
            "romaji": "Ōkii hon o tabemasu.",
            "translation": "Como el libro grande.",
            "is_correct": False,
        },
        {
            "text_jp": "大きい水を読みます。",
            "furigana": "おおきいみずをよみます。",
            "romaji": "Ōkii mizu o yomimasu.",
            "translation": "Leo el agua grande.",
            "is_correct": False,
        },
        {
            "text_jp": "大きい山を飲みました。",
            "furigana": "おおきいやまをのみました。",
            "romaji": "Ōkii yama o nomimashita.",
            "translation": "Bebí la montaña grande.",
            "is_correct": False,
        },
    ],
    "小": [
        {
            "text_jp": "小さい水を食べます。",
            "furigana": "ちいさいみずをたべます。",
            "romaji": "Chiisai mizu o tabemasu.",
            "translation": "Como el agua pequeña.",
            "is_correct": False,
        },
        {
            "text_jp": "小さい本を飲みます。",
            "furigana": "ちいさいほんをのみます。",
            "romaji": "Chiisai hon o nomimasu.",
            "translation": "Bebo el libro pequeño.",
            "is_correct": False,
        },
        {
            "text_jp": "小さい山を読みました。",
            "furigana": "ちいさいやまをよみました。",
            "romaji": "Chiisai yama o yomimashita.",
            "translation": "Leí la montaña pequeña.",
            "is_correct": False,
        },
    ],
    "長": [
        {
            "text_jp": "長い本を食べます。",
            "furigana": "ながいほんをたべます。",
            "romaji": "Nagai hon o tabemasu.",
            "translation": "Como el libro largo.",
            "is_correct": False,
        },
        {
            "text_jp": "長い水を読みます。",
            "furigana": "ながいみずをよみます。",
            "romaji": "Nagai mizu o yomimasu.",
            "translation": "Leo el agua larga.",
            "is_correct": False,
        },
        {
            "text_jp": "長い石を飲みました。",
            "furigana": "ながいいしをのみました。",
            "romaji": "Nagai ishi o nomimashita.",
            "translation": "Bebí la piedra larga.",
            "is_correct": False,
        },
    ],
    "高": [
        {
            "text_jp": "高い水を食べます。",
            "furigana": "たかいみずをたべます。",
            "romaji": "Takai mizu o tabemasu.",
            "translation": "Como el agua cara.",
            "is_correct": False,
        },
        {
            "text_jp": "高い本を飲みます。",
            "furigana": "たかいほんをのみます。",
            "romaji": "Takai hon o nomimasu.",
            "translation": "Bebo el libro caro.",
            "is_correct": False,
        },
        {
            "text_jp": "高い山を読みました。",
            "furigana": "たかいやまをよみました。",
            "romaji": "Takai yama o yomimashita.",
            "translation": "Leí la montaña alta.",
            "is_correct": False,
        },
    ],
    "古": [
        {
            "text_jp": "古い水を食べます。",
            "furigana": "ふるいみずをたべます。",
            "romaji": "Furui mizu o tabemasu.",
            "translation": "Como el agua vieja.",
            "is_correct": False,
        },
        {
            "text_jp": "古い本を飲みます。",
            "furigana": "ふるいほんをのみます。",
            "romaji": "Furui hon o nomimasu.",
            "translation": "Bebo el libro viejo.",
            "is_correct": False,
        },
        {
            "text_jp": "古い山を読みました。",
            "furigana": "ふるいやまをよみました。",
            "romaji": "Furui yama o yomimashita.",
            "translation": "Leí la montaña vieja.",
            "is_correct": False,
        },
    ],
    "新": [
        {
            "text_jp": "新しい水を食べます。",
            "furigana": "あたらしいみずをたべます。",
            "romaji": "Atarashii mizu o tabemasu.",
            "translation": "Como el agua nueva.",
            "is_correct": False,
        },
        {
            "text_jp": "新しい本を飲みます。",
            "furigana": "あたらしいほんをのみます。",
            "romaji": "Atarashii hon o nomimasu.",
            "translation": "Bebo el libro nuevo.",
            "is_correct": False,
        },
        {
            "text_jp": "新しい山を読みました。",
            "furigana": "あたらしいやまをよみました。",
            "romaji": "Atarashii yama o yomimashita.",
            "translation": "Leí la montaña nueva.",
            "is_correct": False,
        },
    ],
    "多": [
        {
            "text_jp": "多い水を食べます。",
            "furigana": "おおいみずをたべます。",
            "romaji": "Ōi mizu o tabemasu.",
            "translation": "Como mucha agua.",
            "is_correct": False,
        },
        {
            "text_jp": "多い本を飲みました。",
            "furigana": "おおいほんをのみました。",
            "romaji": "Ōi hon o nomimashita.",
            "translation": "Bebí muchos libros.",
            "is_correct": False,
        },
        {
            "text_jp": "多い石を読みます。",
            "furigana": "おおいいしをよみます。",
            "romaji": "Ōi ishi o yomimasu.",
            "translation": "Leo muchas piedras.",
            "is_correct": False,
        },
    ],
    "少": [
        {
            "text_jp": "少ない水を食べます。",
            "furigana": "すくないみずをたべます。",
            "romaji": "Sukunai mizu o tabemasu.",
            "translation": "Como poca agua.",
            "is_correct": False,
        },
        {
            "text_jp": "少ない本を飲みます。",
            "furigana": "すくないほんをのみます。",
            "romaji": "Sukunai hon o nomimasu.",
            "translation": "Bebo pocos libros.",
            "is_correct": False,
        },
        {
            "text_jp": "少ない山を読みました。",
            "furigana": "すくないやまをよみました。",
            "romaji": "Sukunai yama o yomimashita.",
            "translation": "Leí pocas montañas.",
            "is_correct": False,
        },
    ],
    "安": [
        {
            "text_jp": "安い水を食べます。",
            "furigana": "やすいみずをたべます。",
            "romaji": "Yasui mizu o tabemasu.",
            "translation": "Como el agua barata.",
            "is_correct": False,
        },
        {
            "text_jp": "安い本を飲みました。",
            "furigana": "やすいほんをのみました。",
            "romaji": "Yasui hon o nomimashita.",
            "translation": "Bebí el libro barato.",
            "is_correct": False,
        },
        {
            "text_jp": "安い山を読みます。",
            "furigana": "やすいやまをよみます。",
            "romaji": "Yasui yama o yomimasu.",
            "translation": "Leo la montaña barata.",
            "is_correct": False,
        },
    ],
    "早": [
        {
            "text_jp": "早い水を食べます。",
            "furigana": "はやいみずをたべます。",
            "romaji": "Hayai mizu o tabemasu.",
            "translation": "Como el agua temprana.",
            "is_correct": False,
        },
        {
            "text_jp": "早い本を飲みます。",
            "furigana": "はやいほんをのみます。",
            "romaji": "Hayai hon o nomimasu.",
            "translation": "Bebo el libro temprano.",
            "is_correct": False,
        },
        {
            "text_jp": "早い石を読みました。",
            "furigana": "はやいいしをよみました。",
            "romaji": "Hayai ishi o yomimashita.",
            "translation": "Leí la piedra temprana.",
            "is_correct": False,
        },
    ],
    "白": [
        {
            "text_jp": "白いカラスを見ます。",
            "furigana": "しろいカラスをみます。",
            "romaji": "Shiroi karasu o mimasu.",
            "translation": "Veo un cuervo blanco.",
            "is_correct": False,
        },
        {
            "text_jp": "白い水を食べます。",
            "furigana": "しろいみずをたべます。",
            "romaji": "Shiroi mizu o tabemasu.",
            "translation": "Como el agua blanca.",
            "is_correct": False,
        },
        {
            "text_jp": "白い本を飲みました。",
            "furigana": "しろいほんをのみました。",
            "romaji": "Shiroi hon o nomimashita.",
            "translation": "Bebí el libro blanco.",
            "is_correct": False,
        },
    ],
    "黒": [
        {
            "text_jp": "黒い雪が降ります。",
            "furigana": "くろいゆきがふります。",
            "romaji": "Kuroi yuki ga furimasu.",
            "translation": "Cae nieve negra.",
            "is_correct": False,
        },
        {
            "text_jp": "黒い水を食べます。",
            "furigana": "くろいみずをたべます。",
            "romaji": "Kuroi mizu o tabemasu.",
            "translation": "Como el agua negra.",
            "is_correct": False,
        },
        {
            "text_jp": "黒い本を飲みます。",
            "furigana": "くろいほんをのみます。",
            "romaji": "Kuroi hon o nomimasu.",
            "translation": "Bebo el libro negro.",
            "is_correct": False,
        },
    ],
    "赤": [
        {
            "text_jp": "赤い空を飲みます。",
            "furigana": "あかいそらをのみます。",
            "romaji": "Akai sora o nomimasu.",
            "translation": "Bebo el cielo rojo.",
            "is_correct": False,
        },
        {
            "text_jp": "赤い水を食べました。",
            "furigana": "あかいみずをたべました。",
            "romaji": "Akai mizu o tabemashita.",
            "translation": "Comí el agua roja.",
            "is_correct": False,
        },
        {
            "text_jp": "赤い雪が降ります。",
            "furigana": "あかいゆきがふります。",
            "romaji": "Akai yuki ga furimasu.",
            "translation": "Cae nieve roja.",
            "is_correct": False,
        },
    ],
    "青": [
        {
            "text_jp": "青い水を食べます。",
            "furigana": "あおいみずをたべます。",
            "romaji": "Aoi mizu o tabemasu.",
            "translation": "Como el agua azul.",
            "is_correct": False,
        },
        {
            "text_jp": "青い本を飲みました。",
            "furigana": "あおいほんをのみました。",
            "romaji": "Aoi hon o nomimashita.",
            "translation": "Bebí el libro azul.",
            "is_correct": False,
        },
        {
            "text_jp": "青い火を読みます。",
            "furigana": "あおいひをよみます。",
            "romaji": "Aoi hi o yomimasu.",
            "translation": "Leo el fuego azul.",
            "is_correct": False,
        },
    ],
}
